addons: 
  apt: 
    packages: 
      - xsltproc
language: python
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libxml2-utils
python: 
  - "3.6" 
script: "xmllint --xinclude --noout --dtdvalid schema/tei_all.dtd header.xml"
